### ISSUE TITLE
Postback Prioritized over Referral

### ISSUE THREAD

**Issue by davidrussell731** [ShellMonkeys/fb-messenger-es6#16]
When you scan a parametric code without having the bot, and click 'Get Started', the referral ref is ignored and the message is treated as simply a postback.  This loses context.

Change order of message parsing on incoming message.

`{
    "object": "page",
    "entry": [
        {
            "id": "624218044111111",
            "time": 1493736336711,
            "messaging": [
                {
                    "recipient": {
                        "id": "624218044111111"
                    },
                    "timestamp": 1493736336711,
                    "sender": {
                        "id": "1439469919111111"
                    },
                    "postback": {
                        "payload": "Start",
                        "referral": {
                            "source": "MESSENGER_CODE",
                            "type": "OPEN_THREAD",
                            "ref": "my-referral-payback"
                        }
                    }
                }
            ]
        }
    ]
}`

**Comment by radTuti** [comment]
Looks like a new update to postback doc that was skipped https://developers.facebook.com/docs/messenger-platform/webhook-reference/postback

**Comment by radTuti** [comment]
Implementors of lib decide if to prioritize referral in postback over postback message or vice versa
