### ISSUE TITLE
@types file

### ISSUE THREAD

**Issue by pdashford** [ShellMonkeys/fb-messenger-es6#30]
Could you provide a types file and some more examples on the message types etc?

**Comment by davidrussell731** [comment]
What do you mean types file?

Is there a specific message type example you want to see?

**Comment by pdashford** [comment]
I'm using the library within typescript, so if you had a typings file then It would present the available options using intellisense.

**Comment by radTuti** [comment]
@pdashford feel free to create a pr to add raw type files.

what message type example do you think is lacking?
